version: "3.8"

networks:
  telegram:
    driver: bridge

# Command в докер compose переопределяет CMD в Dockerfile
services:
  php-fpm-exporter:
    image: bakins/php-fpm-exporter:v0.6.1
    container_name: php-fpm-exporter
    restart: unless-stopped
    command: ["--endpoint", "http://nginx/status-fpm", "--addr", "0.0.0.0:8080"]
    ports:
      - "9253:8080"
    networks:
      - telegram