{
 "title": "PHP-FPM",
 "description": "PHP-FPM monitoring dashboard",
 "tags": [ "php-fpm" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(phpfpm_up, job)" },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(phpfpm_up {job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(phpfpm_up{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Accepted Connections",
   "type": "graph",
   "description": " Total number of accepted connections as irate in a range of 5 minutes",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(phpfpm_accepted_connections_total{instance=~\"$node:$port\",job=\"$job\"}[5m])",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_processes_total{instance=~\"$node:$port\",job=\"$job\",state=\"idle\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "phpfpm_processes_total{instance=~\"$node:$port\",job=\"$job\",state=\"active\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "sum by (instance,statte) (phpfpm_processes_total{instance=~\"$node:$port\",job=\"$job\"})",
     "legendFormat": " Total"
    }
   ]
  },
  {
   "title": "Active Max Processes",
   "type": "graph",
   "description": "The maximum number of active processes since FPM has started",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_active_max_processes{instance=~\"$node:$port\",job=\"$job\"}",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "Max Children Reached",
   "type": "graph",
   "description": "Number of times, the process limit has been reached,\nwhen pm tries to start more children",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_max_children_reached_total{instance=~\"$node:$port\",job=\"$job\"}",
     "legendFormat": "Max children reached"
    }
   ]
  },
  {
   "title": "Listen Queue Connections",
   "type": "graph",
   "description": "The number of request in the queue of pending connections",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_listen_queue_connections{instance=~\"$node:$port\",job=\"$job\"}",
     "legendFormat": "Requests in the queue"
    }
   ]
  },
  {
   "title": "Listen Queue Max Connections",
   "type": "graph",
   "description": "The maximum number of requests in the queue\nof pending connections since FPM has started",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_listen_queue_max_connections{instance=~\"$node:$port\",job=\"$job\"}",
     "legendFormat": "Max requests in th equeue"
    }
   ]
  },
  {
   "title": "Listen Queue Length Connections",
   "type": "graph",
   "description": "The length of the socket queue, dictating maximum number of pending connections\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_listen_queue_length_connections{instance=~\"$node:$port\",job=\"$job\"}",
     "legendFormat": "Length of the socket queue"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "graph",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_slow_requests_total{instance=~\"$node:$port\",job=\"$job\"}",
     "legendFormat": "Slow requests"
    }
   ]
  }
 ]
}